# Generated by Django 4.1.7 on 2024-02-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grabaciones', models.JSONField()),
                ('indices_seleccionados', models.JSONField()),
                ('valores', models.JSONField()),
                ('csv_path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='IndicesData',
        ),
    ]
