# Generated by Django 4.1.7 on 2024-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos_completados', models.IntegerField(default=0)),
                ('cantidad_archivos', models.IntegerField(default=0, null=True)),
                ('csv_cargado', models.BooleanField(default=False)),
            ],
        ),
    ]
