# Generated by Django 4.1.7 on 2023-03-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progress',
            new_name='Progreso',
        ),
        migrations.RenameField(
            model_name='progreso',
            old_name='completed',
            new_name='completado',
        ),
    ]
