# Generated by Django 4.1.7 on 2023-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0002_rename_progress_progreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
