# Generated by Django 4.1.7 on 2023-03-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0004_alter_progreso_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='cantidad',
            new_name='cantidad_archivos',
        ),
    ]
