# Generated by Django 4.1.7 on 2023-03-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0005_rename_cantidad_progreso_cantidad_archivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='completado',
            new_name='archivos_completados',
        ),
    ]
