# Generated by Django 4.1.7 on 2023-03-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0006_rename_completado_progreso_archivos_completados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
