# Generated by Django 4.1.7 on 2023-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procesamiento', '0007_delete_progreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos_completados', models.IntegerField(default=0)),
                ('cantidad_archivos', models.IntegerField(default=100, null=True)),
            ],
        ),
    ]
