# Generated by Django 4.1.7 on 2024-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0010_progreso_uno_porciento'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='csv_cargado',
            field=models.BooleanField(default=False),
        ),
    ]
