# Generated by Django 4.1.7 on 2024-02-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento', '0011_progreso_csv_cargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='uno_porciento',
        ),
    ]
