# Generated by Django 4.1.7 on 2024-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardadoClusterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodologiaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_clasifi', models.JSONField(default=list, null=True)),
                ('mean_class', models.JSONField(default=list, null=True)),
                ('infoZC', models.JSONField(default=list, null=True)),
                ('gadso', models.JSONField(default=list, null=True)),
                ('representativo', models.JSONField(default=list, null=True)),
                ('dispersion', models.JSONField(default=list, null=True)),
                ('frecuencia', models.JSONField(default=list, null=True)),
            ],
        ),
    ]
