# Generated by Django 3.2.18 on 2023-09-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado_auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodologiaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.TextField()),
                ('datos_clasifi', models.JSONField()),
                ('mean_class', models.JSONField()),
                ('infoZC', models.JSONField()),
                ('gadso', models.JSONField()),
                ('representativo', models.JSONField()),
                ('dispersion', models.JSONField()),
                ('frecuencia', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='TableData',
        ),
    ]
