# Generated by Django 3.2.18 on 2023-09-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado_auto', '0002_auto_20230904_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodologiaresult',
            name='table',
        ),
    ]
