# Generated by Django 3.2.18 on 2023-09-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado_auto', '0003_remove_metodologiaresult_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodologiaresult',
            name='datos_clasifi',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='dispersion',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='frecuencia',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='gadso',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='infoZC',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='mean_class',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='representativo',
            field=models.JSONField(null=True),
        ),
    ]
