# Generated by Django 3.2.18 on 2023-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado_auto', '0004_auto_20230904_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodologiaresult',
            name='datos_clasifi',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='dispersion',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='frecuencia',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='gadso',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='infoZC',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='mean_class',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='metodologiaresult',
            name='representativo',
            field=models.JSONField(default=list, null=True),
        ),
    ]
