# Generated by Django 4.1.7 on 2023-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado_auto', '0005_auto_20230905_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardadoClusterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
